# Generated by Django 5.2.1 on 2025-07-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_remove_language_created_at_and_more'),
        ('oms', '0003_alter_order_options_remove_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='productlang',
            name='lang',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.language'),
        ),
    ]
