# Generated by Django 5.2.1 on 2025-07-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_remove_language_created_at_and_more'),
        ('oms', '0004_alter_product_options_alter_productlang_lang'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlang',
            unique_together={('product', 'lang')},
        ),
    ]
